PrimerMvcNetCore/Models/ErrorViewModel.cs
namespace PrimerMvcNetCore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PrimerMvcNetCore/Models/Persona.cs
namespace PrimerMvcNetCore.Models
{
    public class Persona
    {
        public string Nombre { get; set; }
        public string Email { get; set; }
        public int Edad { get; set; }
    }
}

PrimerMvcNetCore/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PrimerMvcNetCore.Models;

namespace PrimerMvcNetCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PrimerMvcNetCore/Controllers/InformacionController.cs
using Microsoft.AspNetCore.Mvc;
using PrimerMvcNetCore.Models;

namespace PrimerMvcNetCore.Controllers
{
    public class InformacionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ControladorVista()
        {
            //VAMOS A ENVIAR INFORMACION SIMPLE A NUESTRA VISTA
            ViewData["NOMBRE"] = "Alumno";
            ViewData["EDAD"] = 24;
            ViewBag.DiaSemana = "Lunes";
            return View();
        }

        public IActionResult VistaControllerGet
            (string saludo, System.Nullable<int> year)
        {

            if (saludo != null)
            {
                ViewData["DATA"] = "Hola " + saludo
                + " en el año " + year;
            } else
            {
                ViewData["DATA"] = "Aquí no hay nada...";
            }

            if (year != null)
            {
                ViewData["DATA"] = "Hola " + saludo
                + " en el año " + year;
            }
            else
            {
                ViewData["DATA"] = "Aquí no tenemos año...";
            }
            return View();
        }

        public IActionResult ControladorVistaModel()
        {
            Persona persona = new Persona();
            persona.Nombre = "Alumno";
            persona.Email = "alumno@email.com";
            persona.Edad = 27;
            return View(persona);
        }

        public IActionResult VistaControllerPost
            (string cajanombre, string cajaemail, int cajaedad)
        {
            ViewData["DATA"] = "Nombre: " + cajanombre
                + ", Email: " + cajaemail
                + ", Edad: " + cajaedad;
            return View();
        }
    }
}

PrimerMvcNetCore/Controllers/MatematicasController.cs
using Microsoft.AspNetCore.Mvc;

namespace PrimerMvcNetCore.Controllers
{
    public class MatematicasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult SumarNumerosGet
        (int numero1, int numero2)
        {
            int suma = numero1 + numero2;
            ViewData["MENSAJE"] = "La suma de "
                + numero1 + " + " + numero2
                + " = " + suma;
            return View();
        }

        public IActionResult ConjeturaCollatz()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ConjeturaCollatz(int numero)
        {
            //DEBEMOS DEVOLVER UN OBJETO COMPLEJO CON
            //UNA LISTA DE NÚMEROS
            List<int> numeros = new List<int>();
            while (numero != 1)
            {
                if (numero % 2 == 0) 
                {
                    numero = numero / 2;
                }
                else
                {
                    numero = numero * 3 + 1;
                }
                numeros.Add(numero);
            }
            //DEVOLVEMOS EL MODEL A LA VISTA
            return View(numeros);
        }

        public IActionResult SumarNumerosPost()
        {
            return View();
        }

        [HttpPost]
        public IActionResult
            SumarNumerosPost(int numero1, int numero2)
        {
            int suma = numero1 + numero2;
            ViewData["MENSAJE"] = "La suma de "
                + numero1 + " + " + numero2
                + " = " + suma;
            return View();
        }

        public IActionResult TablaMultiplicarSimple()
        {
            return View();
        }

        [HttpPost]
        public IActionResult TablaMultiplicarSimple(int numero)
        {
            // LISTA PARA ALMACENAR LOS RESULTADOS DE LA TABLA
            List<int> numeros = new List<int>();

            // GENERAR LA TABLA DE MULTIPLICAR DESDE 1 HASTA 10
            for (int i = 1; i <= 10; i++)
            {
                numeros.Add(numero * i);
            }

            // DEVOLVEMOS EL MODEL A LA VISTA
            return View(numeros);
        }

    }
}

PrimerMvcNetCore/Controllers/PruebaController.cs
using Microsoft.AspNetCore.Mvc;

namespace PrimerMvcNetCore.Controllers
{
    public class PruebaController : Controller
    {
        public IActionResult PrimeraPagina()
        {
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

PrimerMvcNetCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PrimerMvcNetCore/Views/Informacion/ControladorVista.cshtml
<h1 style="color:blue">
	Informacion Controller --> View
</h1>
<h2>Nombre @ViewData["NOMBRE"]</h2>
<h2>Edad @ViewData["EDAD"]</h2>
<h2>Día semana @ViewBag.DiaSemana</h2>

PrimerMvcNetCore/Views/Informacion/ControladorVistaModel.cshtml
@model Persona

<h1>
	Información Controller --> View Model
</h1>

<h2 style="color:aqua">
	@Model.Nombre, @Model.Email, @Model.Edad
</h2>

PrimerMvcNetCore/Views/Informacion/Index.cshtml
<h1>Menu informacion</h1>
<ul>
	<li>
		@Html.ActionLink("Vista Controller Get", "VistaControllerGet",
		"Informacion", new {saludo = "Hola caracola", year = 2025})
	</li>
	<li>
		@Html.ActionLink("Vista Controller Get Sin Saludo", "VistaControllerGet",
					"Informacion", new { year = 2025 })
	</li>
	<li>
		@Html.ActionLink("Vista Controller Get Sin Año", "VistaControllerGet",
					"Informacion", new { saludo = "Holaaa saludoo"})
	</li>
	<li>
		<a asp-controller="Informacion"
		   asp-action="VistaControllerPost">
	   Vista Controller Post</a>
	</li>
	<li>
		<a asp-controller="Informacion"
		   asp-action="ControladorVista">
			Controlador --> Vista
		</a>
	</li>
	<li>
		<a asp-controller="Informacion"
		   asp-action="ControladorVistaModel">
			Controlador --> Vista Model
		</a>
	</li>
</ul>

PrimerMvcNetCore/Views/Informacion/VistaControllerGet.cshtml
<h1>
	Informacion Vista -> Controller Get
</h1>

<h2 style="color:red">
	@ViewData["DATA"]
</h2>

PrimerMvcNetCore/Views/Informacion/VistaControllerPost.cshtml
<h1 style="color:blue">
	Vista Controller POST
</h1>

<form method="post">
	<label>Nombre</label>
	<input type="text" name="cajanombre" class="form-control" />
	<br/>
	<label>Email</label>
	<input type="text" name="cajaemail" class="form-control" />
	<br />
	<label>Edad</label>
	<input type="text" name="cajaedad" class="form-control" />
	<br />
	<button class="btn btn-info">
		Enviar informacion
	</button>
</form>
<h2 style="color:lawngreen">@ViewData["DATA"]</h2>

PrimerMvcNetCore/Views/Matematicas/ConjeturaCollatz.cshtml
@model List<int>

<h2>
	Conjetura Collatz
</h2>

<form method="post">
	<label>Número Collatz</label>
	<input type="text" name="numero"
		class="form-control"/>
	<button class="btn btn-warning">
		Mostrar conjetura
	</button>
</form>

@if (Model != null) 
{
	<ul>
		@foreach (int num in Model)
		{
			<li>@num</li>
		}
	</ul>
}

PrimerMvcNetCore/Views/Matematicas/Index.cshtml
<h1>Menu Matematicas</h1>
<ul>
	<li>
		@Html.ActionLink("Sumar 5 + 6", "SumarNumerosGet",
		"Matematicas",
		new {numero1 = 5, numero2 = 6})
	</li>
	<li>
		<a asp-controller="Matematicas"
		   asp-action="SumarNumerosPost">
	   Sumar números Post
	   </a>
	</li>
	<li>
		<a asp-controller="Matematicas"
		   asp-action="ConjeturaCollatz">
			Conjetura Collatz
		</a>
	</li>
	<li>
		<a asp-controller="Matematicas"
		   asp-action="TablaMultiplicarSimple">
			Multiplicar Número
		</a>
	</li>
</ul>

PrimerMvcNetCore/Views/Matematicas/SumarNumerosGet.cshtml
<h1 style="color:blue">
	Sumar Números Get
</h1>
<h3>
	@ViewData["MENSAJE"]
</h3>

PrimerMvcNetCore/Views/Matematicas/SumarNumerosPost.cshtml
<h1 style="color:fuchsia">    Sumar números POST</h1> <form method="post">    <label>Número 1</label>    <input type="text" name="numero1"        class="form-control"/><br/>    <label>Número 2</label>    <input type="text" name="numero2"        class="form-control"/><br/>    <button class="btn btn-success">        Sumar números    </button></form><h3 style="color:red">    @ViewData["MENSAJE"]</h3>

PrimerMvcNetCore/Views/Matematicas/TablaMultiplicarSimple.cshtml
@model List<int>
<h2>
	Multiplicar
</h2>

<form method="post">
	<label>Número a multiplicar</label>
	<input type="text" name="numero"
		   class="form-control" />
	<button class="btn btn-warning">
		Multiplicar
	</button>
</form>

@if (Model != null)
{
	<ul>
		@foreach (int num in Model)
		{
			<li>@num</li>
		}
	</ul>
}

PrimerMvcNetCore/Views/Prueba/Index.cshtml
@*
    Comentarios en razor
*@
DECLARACIÓN DE VARIABLES A NIVEL DE PÁGINA
@{
    //ESTO ES CÓDIGO C#
    int valor = 14;
    string texto = "hoy es lunes";
    valor += 1;
    texto += " y mañana martes";
    texto = texto.ToUpper();
}
DIBUJAR VARIABLES
<h2 style="color:red">
    Texto: @texto, Número: @valor
</h2>

CÓDIGO LÓGICO CON HTML 
@if(valor > 0){
    //CÓDIGO C#
    texto = "POSITIVO";
    <h3 style="color:lawngreen">@texto</h3>
}else{
    //CÓDIGO C#
    texto = "NEGATIVO";
    <h3 style="color:red">@texto</h3>
}

PrimerMvcNetCore/Views/Prueba/PrimeraPagina.cshtml
<h1 style="color:blue">
	Holaa
</h1>

PrimerMvcNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrimerMvcNetCore</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrimerMvcNetCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrimerMvcNetCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               asp-controller="Matematicas"
                               asp-action="Index">
                                Matematicas
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" 
                            asp-controller="Informacion"
                            asp-action="Index">
                            Información
                        </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <a asp-controller="Prueba" asp-action="PrimeraPagina">
            Mi primera página
        </a>
        <a asp-controller="Prueba" asp-action="Index">
            Código Razor
        </a>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PrimerMvcNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>